# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=256)),
                ('summary', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('slug', models.SlugField(default='')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'tags',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(related_name='tags_ids', to='home.Tags'),
        ),
    ]
