# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firt_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('role', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-id'],
            },
        ),
    ]
