# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 08:11
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_tags_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
