# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_tags_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
    ]
