# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20160627_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='description',
        ),
    ]
